name: pos_flutter
description: Offline-first POS (Windows + Android) with thermal printing
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.2+1
  # Printing utilities
  esc_pos_utils: ^1.1.0
  esc_pos_printer: ^4.1.0
  # Android Bluetooth printer plugin (Android only)
  blue_thermal_printer: ^1.1.5
  # Windows printing (FFI)
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
